create table elementos_tecnologicos (
	numero_serie INT,
	ciudad VARCHAR(50),
	precio DECIMAL(5,1),
	fecha_fabricacion DATE,
	vendedor VARCHAR(50)
);
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (1, 'Kukawa', 996.8, '26/03/2001', 'Nerita Diviny');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (2, 'Tongyu', 879.8, '20/02/2011', 'Charmaine Krystek');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (3, 'Fengcheng', 579.8, '19/09/2012', 'Alanah Larimer');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (4, 'Bayang', 741.1, '23/08/2008', 'Zeb Preene');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (5, 'Bolian', 331.3, '18/08/2007', 'Haydon Mitton');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (6, 'Saint Andrews', 406.8, '31/07/2011', 'Gale Benninger');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (7, 'Österbybruk', 15.4, '27/05/2011', 'Arlinda Ordidge');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (8, 'Gornji Breg', 147.5, '26/01/2005', 'Marlo Scneider');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (9, 'Verblyany', 474.6, '03/10/2023', 'Mara Al Hirsi');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (10, 'Nantes', 611.3, '13/08/2008', 'Giffie Henniger');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (11, 'Gashua', 850.9, '04/03/2001', 'Vaughn Bonnette');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (12, 'Luau', 810.2, '05/04/2024', 'Penrod Rudgard');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (13, 'Margara', 546.8, '19/10/2012', 'Sammy Guerreau');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (14, 'Ibrā’', 497.9, '01/04/2019', 'Deana Swadden');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (15, 'Bohorodchany', 843.2, '16/09/2002', 'Fredericka Olligan');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (16, 'Chengzhai', 823.1, '01/07/2012', 'Yanaton Brierley');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (17, 'Krupka', 306.3, '06/06/2002', 'Albertina Le Huquet');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (18, 'Baoping', 52.4, '04/10/2002', 'Mirabelle Bozier');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (19, 'Warungsugan', 71.3, '30/04/2011', 'Steffane Goodfellow');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (20, 'Chacarita', 403.5, '06/11/2015', 'Zonnya Elphick');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (21, 'La Maná', 705.5, '08/12/2002', 'Granville Raffels');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (22, 'Bang Kruai', 804.7, '29/04/2017', 'Chandal Marguerite');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (23, 'Eslöv', 760.8, '28/07/2013', 'Yelena Smoote');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (24, 'Namling', 487.3, '02/01/2005', 'Sander Barrie');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (25, 'Calape', 614.2, '13/09/2021', 'Rudolfo Pulbrook');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (26, 'Baranów', 129.7, '05/11/2004', 'Suzi Fyall');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (27, 'Pedro Juan Caballero', 841.0, '04/06/2022', 'Horton McCann');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (28, 'Shichuan', 291.8, '18/02/2004', 'Arlen Wilmut');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (29, 'Jesenice', 26.1, '09/07/2002', 'Larina Hasnip');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (30, 'Loimaan Kunta', 423.8, '25/09/2009', 'Reggis Brislen');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (31, 'Papágou', 328.3, '25/08/2020', 'Kermie Cranstone');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (32, 'Blagoevgrad', 316.3, '10/01/2009', 'Diena Rehme');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (33, 'Baranti', 995.5, '11/11/2016', 'Marietta Kitt');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (34, 'Cầu Giấy', 886.1, '24/07/2009', 'Kevon Rosettini');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (35, 'San José de los Remates', 261.5, '18/01/2013', 'Letisha Waddie');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (36, 'Hotsk', 463.8, '17/09/2007', 'Delano Sharrem');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (37, 'Sapeken', 776.0, '19/06/2001', 'Willdon Novill');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (38, 'Bendo', 513.8, '11/03/2014', 'Kenton MacMarcuis');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (39, 'Jiuzhou', 196.8, '10/09/2020', 'Stevy Stilldale');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (40, 'Qianhong', 755.7, '11/08/2017', 'Timi Tease');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (41, 'Regla', 295.3, '19/02/2008', 'Ardelia Withinshaw');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (42, 'Moriguchi', 134.6, '07/02/2015', 'Darwin Battlestone');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (43, 'Sinubong', 630.2, '20/06/2017', 'Artus Kingswood');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (44, 'Nikol’skoye', 64.9, '09/05/2013', 'Corabella Gumm');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (45, 'Porto Salvo', 23.2, '25/10/2007', 'Michaela Oubridge');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (46, 'Elói Mendes', 521.2, '10/09/2002', 'Ursula Maund');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (47, 'Yangi-Nishon Shahri', 96.1, '08/07/2002', 'Wilbur Toope');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (48, 'Beaumont', 749.4, '23/10/2002', 'Ramon Kingzet');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (49, 'Donegal', 857.1, '23/02/2023', 'Fabiano Shillaber');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (50, 'Małdyty', 6.3, '06/10/2006', 'Brana Darrell');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (51, 'Morioka-shi', 217.9, '01/07/2006', 'Jabez Biernacki');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (52, 'Pābna', 681.7, '29/04/2012', 'Melva Perrone');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (53, 'Moita', 348.8, '10/07/2000', 'Waldon Eberst');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (54, 'Hufang', 910.8, '25/10/2019', 'Ainslie Sollitt');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (55, 'Chenghuang', 510.3, '25/12/2019', 'Orrin Wilbore');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (56, 'Czerniewice', 487.0, '09/07/2021', 'Vanya Garfitt');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (57, 'Garibaldi', 66.5, '14/02/2016', 'Sosanna Lamlin');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (58, 'Nikinci', 6.0, '13/09/2013', 'Idalia Pinnock');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (59, 'Badar', 215.9, '15/04/2013', 'Ardis Hatwell');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (60, 'Dongba', 459.6, '17/09/2002', 'Cornall Shawyers');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (61, 'Goiás', 818.6, '17/04/2024', 'Rivy Pourvoieur');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (62, 'Mokwa', 504.4, '28/03/2006', 'Matt Skyner');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (63, 'At Tibnī', 93.7, '26/05/2006', 'Geoffrey Gratrix');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (64, 'Chumphon', 532.9, '16/07/2015', 'Angelle Dixcee');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (65, 'Calabaca', 877.7, '10/04/2005', 'Delores Brigstock');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (66, 'Zhongdeng', 123.4, '22/03/2010', 'Kelby Rozet');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (67, 'Ovidiopol’', 203.8, '18/11/2023', 'Alanah Nestle');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (68, 'Zaragoza', 241.3, '23/12/2009', 'Birdie Izak');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (69, 'Quilo-quilo', 355.4, '29/07/2006', 'Cris McOwen');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (70, 'Malāyer', 106.4, '07/11/2009', 'Cristiano Taffarello');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (71, 'Tuanshan', 300.5, '09/01/2010', 'Timothee Wolford');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (72, 'Cusapín', 426.4, '04/11/2020', 'Coraline Daborn');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (73, 'Tarnowskie Góry', 563.3, '13/05/2016', 'Gerty Cajkler');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (74, 'Kampong Chhnang', 14.6, '10/03/2020', 'Josey Guswell');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (75, 'Liurenba', 486.0, '12/10/2016', 'Maurene Waliszek');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (76, 'Tuoshi', 379.8, '23/12/2011', 'Zacharia Ahmed');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (77, 'Mozhaysk', 423.4, '12/03/2002', 'Cam Targett');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (78, 'Hobonio', 258.8, '26/08/2017', 'Lilli Layus');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (79, 'Schirmeck', 796.1, '28/03/2010', 'Querida Kittoe');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (80, 'Fangcun', 315.8, '02/08/2003', 'Hermina Debell');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (81, 'Dondo', 515.8, '26/07/2009', 'Sophie Kelwick');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (82, 'Duas Igrejas', 733.2, '26/11/2015', 'Kylie Addinall');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (83, 'Golub-Dobrzyń', 592.6, '04/04/2019', 'Bing Kleynermans');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (84, 'Kiarajangkung', 341.7, '01/04/2007', 'Joli Barkas');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (85, 'Zhongmen', 827.5, '26/12/2012', 'Willis Sear');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (86, 'Grazhdanka', 121.0, '20/04/2015', 'Shaina Ryder');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (87, 'Shahr-e Bābak', 319.6, '16/03/2023', 'Tony Peres');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (88, 'Korczyna', 33.0, '28/02/2013', 'Jane Fulle');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (89, 'Bireun', 804.0, '03/08/2020', 'Stanislaw Allum');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (90, 'San Pa Tong', 958.5, '05/12/2007', 'Whit Kingzeth');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (91, 'Atouguia', 160.9, '28/02/2004', 'Lida Beaby');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (92, 'Zbraslav', 328.5, '22/11/2017', 'Sascha Durman');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (93, 'El Paso', 962.3, '09/03/2018', 'Kristo Everingham');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (94, 'Fresnes', 792.1, '23/09/2013', 'Carin Luckham');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (95, 'Cagwait', 913.4, '22/01/2007', 'Johnna Lammin');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (96, 'Bang Rakam', 80.8, '07/01/2018', 'Shelley Athy');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (97, 'New Bedford', 205.5, '17/12/2003', 'Eachelle Poulglais');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (98, 'San Isidro', 252.6, '11/02/2024', 'Dag Mantz');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (99, 'Wenheng', 921.0, '19/09/2014', 'Ondrea Greenacre');
insert into elementos_tecnologicos (numero_serie, ciudad, precio, fecha_fabricacion, vendedor) values (100, 'Colorado Springs', 792.1, '01/10/2020', 'Markus Rainford');
